name: React build
on: 
#   workflow_dispatch:
#     inputs:
#       name:
#         description: 'Person to greet'
#         required: true
#         default: 'Mona the Octocat'
#       home:
#         description: 'location'
#         required: false
#         default: 'The Octoverse'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main
        uses: actions/checkout@main
        
      - name: Install dependencies
        run: npm install

      - name: Build 
        run: npm run build
#         env:
#           CI: False
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.



# name: React build
# on: 
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-18.04
#     steps:
#       - name: Checkout main
#         uses: actions/checkout@main
        
#       - name: Cache node modules
#         uses: actions/cache@v1
#         with:
#           path: node_modules # ìºì‹œë¥¼ ì €ì¥í•˜ê±°ë‚˜ ë³µì›í•  ë””ë ‰í† ë¦¬
#           key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }} # ìºì‹œë¥¼ ì €ì¥í•˜ê±°ë‚˜ ë³µì›í•  ë•Œ ì‚¬ìš©ë˜ëŠ” ìœ ë‹ˆí¬í•œ í‚¤ ê°’
#           restore-keys: | # í‚¤ ê°’ì´ ê¸°ì¡´ì˜ ìºì‹œì™€ ì¼ì¹˜í•˜ì§€ ì•ŠëŠ” ê²½ìš° ì‚¬ìš©ë˜ëŠ” ëŒ€ì²´ í‚¤ ê°’ ë¦¬ìŠ¤íŠ¸(optional)
#             ${{ runner.OS }}-build-
#             ${{ runner.OS }}-
#       - name: Install dependencies
#         run: npm install

#       - name: Build 
#         run: npm run build
        
#       - name: Deploy to S3
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: |
#           aws s3 cp \
#             --recursive \
#             --region ap-northeast-2 \
#             dist s3://vmc-front-prd
